#!/usr/bin/env python

import cherrypy
from ocauth.authservice import Root

conf = {
    'global': {
        'server.socket_host': '0.0.0.0',
        'server.socket_port': 8087
     },
     '/' : { 
        'tools.proxy.on':True
     }
}

cherrypy.quickstart(Root(), '/', conf)
