#!/bin/bash
#
# Cherrypy Application Start
#

# Source function library.
. /etc/rc.d/init.d/functions

prog="Orange Cloud Auth Service"
appctl=/usr/local/bin/ocauthservd
dirapp=/usr/local/bin/
lockfile=/var/lock/ocauth.lock

start() {
        echo -n $"Starting $prog"
        cd $dirapp
        touch $lockfile
        $appctl &
}
stop() {
        echo -n $"Stopping $prog"
        echo
        pid=`/bin/ps -ef | grep your_app.py | grep -v grep | awk '{print $2}'`
        kill -9 $pid && rm -f ${lockfile}
        echo
        echo 'ok'
}

# See how we were called.
case "$1" in
  restart)
        stop
        start
        ;;
  start)
        start
        ;;
  stop)
        stop
        ;;
  *)
        echo $"Usage: $prog {start|stop|restart}"
        exit 1
esac

